services:
  next-app:
    container_name: parallel-routes
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/src
      - ./public:/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
